// action常量
export const GETSERVERS = 'GETSERVERS'
export const GETPRODUCTS = 'GETPRODUCTS'
export const GETTABLES = 'GETTABLES'
export const GETLOADING = 'GETLOADING'
export const GETROWKEYS = 'GETROWKEYS'
export const GETCURPRODUCT = 'GETCURPRODUCT'
export const GETSEARCH = 'GETSEARCH'
export const REFRESHSEARCH = 'REFRESHSEARCH'

